services:
  app-dist:
    build: 
      context: .
      dockerfile: ./docker/production-dist/Dockerfile 
      target: dist
    profiles:
      - dist
    container_name: ${PROJECT_PREFIX}-dist
    hostname: ${PROJECT_PREFIX}-dist
    ports:
      - ${APP_WEB_DIST_PORT}:80
      - ${DIST_MONGO_DB}:27017
      - ${DIST_WS_PORT}:4000
    env_file:
      - .env

  development:
    build:
      context: .
      dockerfile: ./docker/development-testing/Dockerfile
    container_name: ${PROJECT_PREFIX}
    volumes:
      - .:/app
      - ./docker/development-testing/config/ssh:/root/.ssh/
      - ./docker/development-testing/config/git/.gitconfig:/headless/.gitconfig
      - ./docker/development-testing/config/node/init-script.sh:/usr/local/bin/init-script.sh
      - ./docker/development-testing/config/wallpaper.png:/headless/.config/bg_image.png
    environment:
      - START_YARN_SERVER=${START_YARN_SERVER}
      - SERVER_MODE=${SERVER_MODE}
      - VNC_PW=${DEV_VNC_PW}
      - VNC_RESOLUTION=${DEV_VNC_RESOLUTION}
      - VUE_APP_GQL_HTTP_PORT=${VUE_APP_GQL_HTTP_PORT}
      - VUE_APP_GQL_WS_PORT=${VUE_APP_GQL_WS_PORT}
      - VUE_DEV_PORT=${VUE_DEV_PORT}
      - PORT=${VUE_DEV_PORT}
    working_dir: /app/code
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - ${DEV_VNC_PORT}:5901
      - ${DEV_NO_VNC_PORT}:6901
      - ${VUE_DEV_PORT}:${VUE_DEV_PORT}
    command: sh /usr/local/bin/init-script.sh