name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to Test'
        required: true
        default: master
        type: string

jobs:
  "tests_e2e":
    runs-on: ubuntu-latest

    services:
      api:
        image: jfcodiaz/graphappmsj-api:latest-dev
        ports:
          - 4000:4000

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Prepare Environment
        run: |
          cd code
          cp .env.ci.example .env
          yarn install 

      - name: Run Cypress Tests
        env:
          VUE_APP_API_HOST: localhost
        run: cd code && yarn run test:headless-testing

      - name: Curl to localhost
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4000)
          echo "Response from localhost:4000 - HTTP status code: $response"

      - name: Upload Screenshots and Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            code/cypress/screenshots
            code/cypress/videos
            code/coverage

  "quality_scan":
    runs-on: ubuntu-latest
    needs: ["tests_e2e", "check_lint_and_format"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: code

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=jfcodiaz
            -Dsonar.projectKey=jfcodiaz_GraphAppMsj_vue
            -Dsonar.javascript.lcov.reportPaths=code/coverage/lcov.info
            -Dsonar.qualitygate.wait=true
            -Dsonar.coverage.exclusions=**/code/cypress/**,**/code/coverage/**

  "check_lint_and_format":
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: |
          cd code
          yarn install

      - name: Run Lint
        run: |
          cd code
          yarn run lint
          yarn run format:check
